name: 'copilot-code-review'
description: 'Review pr with AI model'
branding:
  icon: 'compass'
  color: 'orange'
inputs:
  AUTH_TOKEN:
    description: 'Token for using GitHub REST API'
    default: ${{ github.token }}
    required: false
  PR_URL:
    description: 'Pull request url'
    required: true
  APIKEY:
    description: 'APIKEY'
    required: true
  ENDPOINT:
    description: "ENDPOINT"
    required: true
runs:
  using: "composite"
  steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
           python-version: "3.11"
      - name: Show Working Directory
        shell: bash
        run: |
          pwd
          ls
      - name: Set Up Env
        shell: bash
        run: | 
           set -ev
           pwd
           python -m pip install --upgrade pip
           python -m venv env
           chmod +x env/bin/activate
           source ./env/bin/activate
           pip install requests
           pip list -v
      - name: Run Code Review
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPO: ${{ github.repository }}
        run: |
          set -x
          pwd
          ls -a
          ls ../
          echo "job here"
          echo pr number: "$PR_NUMBER"
          echo pr repo: "$PR_REPO"
          chmod +x env/bin/activate
          source env/bin/activate
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Install dependencies
        shell: bash
        run: |
          pwd
          ls
          npm install @azure/openai
          npm install @octokit/rest
          node --version
      - name: Run Scripts
        shell: bash
        env: 
          GITHUB_ACTION_PATH: ${{ github.action_path }}
        run: |
          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      - name: PR Review
        shell: bash
        run: |
          node review-scripts.js